### PR TITLE
formal main, redundant code clean, better src check

### PR DESCRIPTION
**Pull request by mikedesu**
Hello,

I saw this tool posted somewhere recently and decided to check out the source, as I was originally feeling like tweaking the output a bit.

I saw some easy opportunities to clean up your code a bit. 
- There was no formal main, so I added that. It isn't "needed" but helps identify the script entry point. 
- in the `find_subdomains` function, there was some redundant if statements. Reading this code reminded me of myself years ago. My inner optimization-freak decided to clean this up a bit and managed to get rid of some lines. I actually see a bit more to optimize here and will come back later.
- The `is_src` function was trivial. No need to check exception at all, just need to verify the tag is a dictionary and contains a 'src' key.

This is one of my first contributions to someone else's open source project. If you need anything, or have any questions, feel free to reach out to me. 

[\@therealdarkmage](http://twitter.com/therealdarkmage)

### CODE REVIEW

**Comment by Cillian-Collins** [comment]
Hi, thanks for the pull request!

Yeah, it all seems good. I appreciate you taking a look at the code and reviewing it. I'll merge the branch now, and anymore contributions would definitely be appreciated.

**Comment by Cillian-Collins** [comment]
The only change I made, and perhaps it's not needed, is the addition of 2 blank lines before and after a function declaration. It's usually a standard across Python, but with there being large comments at the beginning of most of our function declarations I'm not sure if it's needed. If you think it's better without then that's fine, but I added them back in for now to maintain some consistency with respect to formatting standards.

**Comment by Cillian-Collins** [comment]
Actually just wondering what the purpose of the while loop was? I didn't catch that when I merged. There's also a print statement left in which isn't needed. I'm going to revert that piece back to how it was previously but if you think there's a case for using a while loop over a for loop then we can discuss that.

**Comment by mikedesu** [comment]
That was for debugging purposes. In python, or in languages with foreach
syntax, there is no guarantee your objects will be accessed in index order.
I use while loops in situations where I might want to inspect each object
in order as they are iterated over. It is a bit old school. I was going to
add in a progress bar to keep track of how far into a parse the script
might be. It helps let me know if the script is hanging.

**Comment by Cillian-Collins** [comment]
Yeah I assumed it was for debugging purposes, I don't mind keeping the while loop if there is a purpose for it (such as the progress bar). Just the print statements were making it difficult to read the verbose output.

**Pull request merged**
